services:
  recettesfamille:
    image: ${DOCKER_REGISTRY-}recettesfamille    
    user: "root"
    container_name: recettesfamille.client
    
    networks:
      testnet:
        ipv4_address: 172.26.0.28
    restart: always

    build:
      context: ..
      dockerfile: ./RecettesFamille/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OPENAI_SECRET=${OPENAI_SECRET}
    depends_on:
      - recettesfamille.data
    volumes:
      - /home/data/client:/app/data:ro  # Mapping du volume
      
  recettesfamille.data:
    image: postgres:latest
    container_name: recettesfamille.data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: PGUserPwd
      POSTGRES_DB: recettesfamilledb
    volumes:
      - /home/data/dbRF:/var/lib/postgresql/data

    networks:
      testnet:
        ipv4_address: 172.26.0.29
    ports:
      - "5442:5432"
    restart: always
        
networks:
  testnet:
    external: true
        