<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-RecettesFamille-f509197d-e4c8-4df4-8a02-860845703b36</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	<IncludePrerelease>true</IncludePrerelease>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Components\Pages\Recettes\RecetteBook\BlockDefinitions\Components\**" />
    <Compile Remove="Components\Pages\TravelPlanner\Categories\**" />
    <Compile Remove="Components\Pages\TravelPlanner\Travels\**" />
    <Compile Remove="Properties\PublishProfiles\**" />
    <Content Remove="Components\Pages\Recettes\RecetteBook\BlockDefinitions\Components\**" />
    <Content Remove="Components\Pages\TravelPlanner\Categories\**" />
    <Content Remove="Components\Pages\TravelPlanner\Travels\**" />
    <Content Remove="Properties\PublishProfiles\**" />
    <EmbeddedResource Remove="Components\Pages\Recettes\RecetteBook\BlockDefinitions\Components\**" />
    <EmbeddedResource Remove="Components\Pages\TravelPlanner\Categories\**" />
    <EmbeddedResource Remove="Components\Pages\TravelPlanner\Travels\**" />
    <EmbeddedResource Remove="Properties\PublishProfiles\**" />
    <None Remove="Components\Pages\Recettes\RecetteBook\BlockDefinitions\Components\**" />
    <None Remove="Components\Pages\TravelPlanner\Categories\**" />
    <None Remove="Components\Pages\TravelPlanner\Travels\**" />
    <None Remove="Properties\PublishProfiles\**" />
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BitzArt.Blazor.Cookies.Server" Version="1.5.1" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Cropper.Blazor" Version="1.5.0" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.16.0" />
    <PackageReference Include="Magick.NET.Core" Version="14.16.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.3" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="10.8.3" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
    <PackageReference Include="MudBlazor.Markdown" Version="9.0.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RecettesFamille.Rag\RecettesFamille.Rag.csproj" />
    <ProjectReference Include="..\RecettesFamille.Data.Repository\RecettesFamille.Data.Repository.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Tools\yt-dlp\linux-x64\" />
    <Folder Include="Tools\yt-dlp\win-x64\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Tools\yt-dlp\linux-x64\yt-dlp_linux">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
    <None Update="Tools\yt-dlp\win-x64\yt-dlp.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>